# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cabac2be0c40760f9dfa9c4d5ab227bc88e81e20d4d3e86151c3dcc63075b1f45ac9f04c1a580c27e465460270424602f08b5033b99e355a1bc15c9106b82196

test:
  secret_key_base: dc14b59df90c5ce42850cd96788bff54662012d32f3006752bf5f848e9e7f5265711b68954a9d2ec02741c66dfb637f0ffa3856ea11b54fa2eb3b71d88dca3e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
